### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bjornbytes**
This is an attempt to update the generator to incorporate the latest changes made to vulkan-zig.

There are a few issues with `xr.xml` that prevent this from building successfully right now: When an array is sized using an enum, the length isn't always wrapped in `<enum>` (e.g. `[XR_GUID_SIZE_MSFT]` instead of `[<enum>XR_GUID_SIZE_MSFT</enum>]`).  It looks like the same type of issue was encountered when these bindings were originally authored.  I reported this to the working group, and made fixes manually while testing.

I'm still pretty new to zig, so suggestions are very welcome.  Thanks for making these bindings :)

### CODE REVIEW

**Comment by s-ol** [comment]
Thanks for dusting off the cobwebs! So I guess we should wait for KhronosGroup/OpenXR-Docs to update the XML file again before merging this?

**Comment by bjornbytes** [comment]
I updated the C parser to assume `[NAME]` is really `[<enum>NAME</enum>]` which works around the array issue.  There's still one issue with 1.0.27 related to `XR_EYE_POSITION_COUNT_FB` that's preventing a successful build, which I also submitted a fix for.  In the meantime, I downgraded `examples/xr.xml` here to 1.0.26, which builds successfully.

**Comment by s-ol** [comment]
@bjornbytes the spec `1.0.28` just released, did the XML issues get fixed by chance?
https://github.com/KhronosGroup/OpenXR-Docs/releases/tag/release-1.0.28

**Comment by bjornbytes** [comment]
Nope, my fix to the XML hasn't been merged yet

**Pull request merged**
